#!/bin/sh
pasm -b CapeTestPru.p
#gcc CapeTestController.c -o CapeTestController -lpthread -lprussdrv
#gcc CapeTestController.c -o CapeTestController -lprussdrv

gcc -c CapeTestController.c -o ControllerTemp.o
gcc ControllerTemp.o -lBBBio -lprussdrv -o CapeTestController
